map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.1

plugins:
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  - {name: range_sensor_layer, type: "range_sensor_layer::RangeSensorLayer"}

inflater_layer:
  inflation_radius: 0.3

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: tim551, data_type: LaserScan, topic: /front/scan, marking: true, clearing: true, obstacle_range: 2.5, raytrace_range: 3.0}

range_sensor_layer:
  clear_threshold: 0.4
  mark_threshold: 0.8
  inflate_cone: 0.0
  clear_on_max_reading: false
  topics: [
    "/wheel_drop_sensor/proccessed/front_centre", "/wheel_drop_sensor/proccessed/rear_centre",
    "/wheel_drop_sensor/proccessed/front_left", "/wheel_drop_sensor/proccessed/rear_left",
    "/wheel_drop_sensor/proccessed/front_right", "/wheel_drop_sensor/proccessed/rear_right"
  ]
