local_costmap:
  update_frequency: 50.0
  publish_frequency: 50.0
  width: 10.0
  height: 10.0
  resolution: 0.05
  static_map: false
  rolling_window: true

  plugins:
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
